-- Fresh Oracle install for the Steam Nexus APEX schema.
-- This file is based on the Object Browser DDL pasted in chat and normalized for install.

CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_users PRIMARY KEY,
    username VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(500) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE developers (
    developer_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_developers PRIMARY KEY,
    developer_name VARCHAR2(255) NOT NULL,
    description VARCHAR2(100)
);

CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_categories PRIMARY KEY,
    category_name VARCHAR2(255) NOT NULL,
    CONSTRAINT uq_categories_name UNIQUE (category_name)
);

CREATE TABLE games (
    game_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_games PRIMARY KEY,
    developer_id NUMBER,
    title VARCHAR2(255) NOT NULL,
    price NUMBER(12,2) DEFAULT 0 NOT NULL,
    release_date TIMESTAMP(6) WITH TIME ZONE,
    age_rating VARCHAR2(10),
    description CLOB,
    CONSTRAINT fk_games_developer FOREIGN KEY (developer_id)
        REFERENCES developers (developer_id),
    CONSTRAINT chk_games_price_nonnegative CHECK (price >= 0)
);

CREATE TABLE promotions (
    promo_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_promotions PRIMARY KEY,
    code VARCHAR2(20) NOT NULL,
    discount_percent NUMBER(5,2),
    start_date TIMESTAMP(6) WITH TIME ZONE,
    end_date TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uq_promotions_code UNIQUE (code),
    CONSTRAINT chk_promotions_discount CHECK (discount_percent BETWEEN 0 AND 100),
    CONSTRAINT chk_promotions_dates CHECK (
        start_date IS NULL OR end_date IS NULL OR start_date <= end_date
    )
);

CREATE TABLE wallets (
    wallet_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_wallets PRIMARY KEY,
    user_id NUMBER NOT NULL,
    currency VARCHAR2(3) DEFAULT 'USD',
    balance NUMBER(12,2) DEFAULT 0,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wallets_user UNIQUE (user_id),
    CONSTRAINT fk_wallets_users FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT chk_wallets_balance_nonnegative CHECK (balance >= 0)
);

CREATE TABLE purchases (
    purchase_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_purchases PRIMARY KEY,
    user_id NUMBER NOT NULL,
    purchase_type VARCHAR2(50),
    payment_method VARCHAR2(50),
    status VARCHAR2(50),
    purchase_date TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    promo_id NUMBER,
    CONSTRAINT fk_purchases_users FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_purchases_promotions FOREIGN KEY (promo_id)
        REFERENCES promotions (promo_id),
    CONSTRAINT chk_purchases_status CHECK (
        status IS NULL OR LOWER(status) IN ('completed', 'pending', 'refunded', 'failed')
    ),
    CONSTRAINT chk_purchases_type CHECK (
        purchase_type IS NULL OR LOWER(purchase_type) IN ('game', 'dlc', 'bundle', 'in_game_purchase', 'gift')
    )
);

CREATE TABLE purchases_item (
    purchase_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_purchases_item PRIMARY KEY,
    game_id NUMBER,
    purchase_id NUMBER,
    price_at_purchase NUMBER(12,2) NOT NULL,
    CONSTRAINT fk_pi_games FOREIGN KEY (game_id)
        REFERENCES games (game_id),
    CONSTRAINT fk_pi_purchases FOREIGN KEY (purchase_id)
        REFERENCES purchases (purchase_id)
);

CREATE TABLE library (
    user_id NUMBER,
    game_id NUMBER,
    purchase_id NUMBER,
    added_date TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_library PRIMARY KEY (user_id, game_id),
    CONSTRAINT fk_library_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_library_game FOREIGN KEY (game_id)
        REFERENCES games (game_id),
    CONSTRAINT fk_library_purchases FOREIGN KEY (purchase_id)
        REFERENCES purchases (purchase_id)
);

CREATE TABLE sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_sessions PRIMARY KEY,
    user_id NUMBER NOT NULL,
    game_id NUMBER NOT NULL,
    start_time TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_sessions_users FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_sessions_games FOREIGN KEY (game_id)
        REFERENCES games (game_id),
    CONSTRAINT chk_sessions_time CHECK (
        end_time IS NULL OR start_time IS NULL OR end_time >= start_time
    )
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_reviews PRIMARY KEY,
    user_id NUMBER,
    game_id NUMBER,
    review_type VARCHAR2(50),
    review_text CLOB,
    review_date TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_users FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_reviews_games FOREIGN KEY (game_id)
        REFERENCES games (game_id),
    CONSTRAINT chk_reviews_type CHECK (
        review_type IS NULL OR LOWER(review_type) IN ('positive', 'negative')
    )
);

CREATE TABLE badges (
    badge_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_badges PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    awarded_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_badges_users FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);

CREATE TABLE friends (
    user_id NUMBER,
    friend_id NUMBER,
    CONSTRAINT pk_friends PRIMARY KEY (user_id, friend_id),
    CONSTRAINT fk_friends_user FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_friends_friend FOREIGN KEY (friend_id)
        REFERENCES users (user_id),
    CONSTRAINT chk_friends_not_self CHECK (user_id <> friend_id)
);

CREATE TABLE messages (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_messages PRIMARY KEY,
    sender_id NUMBER,
    receiver_id NUMBER,
    content CLOB NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_read NUMBER(1,0) DEFAULT 0,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_id)
        REFERENCES users (user_id),
    CONSTRAINT chk_messages_is_read CHECK (is_read IN (0, 1))
);

CREATE TABLE achievements (
    achievement_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT pk_achievements PRIMARY KEY,
    game_id NUMBER,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    CONSTRAINT fk_achievements_games FOREIGN KEY (game_id)
        REFERENCES games (game_id)
);

CREATE TABLE user_achievements (
    user_id NUMBER,
    achievement_id NUMBER,
    unlocked_at TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_achievements PRIMARY KEY (user_id, achievement_id),
    CONSTRAINT fk_ua_users FOREIGN KEY (user_id)
        REFERENCES users (user_id),
    CONSTRAINT fk_ua_achievements FOREIGN KEY (achievement_id)
        REFERENCES achievements (achievement_id)
);

CREATE TABLE game_categories (
    game_id NUMBER,
    category_id NUMBER,
    CONSTRAINT pk_game_categories PRIMARY KEY (game_id, category_id),
    CONSTRAINT fk_gc_games FOREIGN KEY (game_id)
        REFERENCES games (game_id),
    CONSTRAINT fk_gc_categories FOREIGN KEY (category_id)
        REFERENCES categories (category_id)
);

CREATE TABLE user_audit_log (
    log_id NUMBER GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_user_audit_log PRIMARY KEY,
    user_id NUMBER,
    action_type VARCHAR2(20),
    old_username VARCHAR2(100),
    new_username VARCHAR2(100),
    action_date DATE
);

CREATE TABLE ddl_log (
    log_id NUMBER GENERATED ALWAYS AS IDENTITY
        CONSTRAINT pk_ddl_log PRIMARY KEY,
    username VARCHAR2(100),
    object_name VARCHAR2(100),
    object_type VARCHAR2(50),
    action_type VARCHAR2(50),
    action_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_achievements_game_id ON achievements (game_id);
CREATE INDEX idx_library_user_id ON library (user_id);
CREATE INDEX idx_messages_conv ON messages (sender_id, receiver_id, SYS_EXTRACT_UTC(sent_at));
CREATE INDEX idx_purchases_user_id ON purchases (user_id);
CREATE INDEX idx_sessions_user_end ON sessions (user_id, SYS_EXTRACT_UTC(end_time));
CREATE INDEX idx_sessions_user_game ON sessions (user_id, game_id);
CREATE INDEX idx_ua_achievement_id ON user_achievements (achievement_id);
CREATE INDEX idx_wallets_user_updated ON wallets (user_id, SYS_EXTRACT_UTC(updated_at));

CREATE OR REPLACE TRIGGER ddl_log_trg
AFTER DDL ON SCHEMA
BEGIN
    IF ORA_DICT_OBJ_NAME <> 'DDL_LOG' THEN
        INSERT INTO ddl_log (
            username,
            object_name,
            object_type,
            action_type,
            action_date
        ) VALUES (
            SYS_CONTEXT('USERENV', 'SESSION_USER'),
            ORA_DICT_OBJ_NAME,
            ORA_DICT_OBJ_TYPE,
            ORA_SYSEVENT,
            CURRENT_TIMESTAMP
        );
    END IF;
END;
/

CREATE OR REPLACE TRIGGER normalization_email_trg
BEFORE INSERT OR UPDATE OF email ON users
FOR EACH ROW
BEGIN
    :NEW.email := LOWER(TRIM(:NEW.email));
END;
/

CREATE OR REPLACE TRIGGER user_audit_trg
FOR INSERT OR UPDATE OR DELETE ON users
COMPOUND TRIGGER
    TYPE t_audit_rec IS RECORD (
        user_id NUMBER,
        action_type VARCHAR2(10),
        old_username VARCHAR2(255),
        new_username VARCHAR2(255)
    );

    TYPE t_audit_tab IS TABLE OF t_audit_rec;
    v_audit_logs t_audit_tab := t_audit_tab();

AFTER EACH ROW IS
BEGIN
    v_audit_logs.EXTEND;

    IF INSERTING THEN
        v_audit_logs(v_audit_logs.LAST).user_id := :NEW.user_id;
        v_audit_logs(v_audit_logs.LAST).action_type := 'INSERT';
        v_audit_logs(v_audit_logs.LAST).new_username := :NEW.username;
    ELSIF UPDATING THEN
        v_audit_logs(v_audit_logs.LAST).user_id := :OLD.user_id;
        v_audit_logs(v_audit_logs.LAST).action_type := 'UPDATE';
        v_audit_logs(v_audit_logs.LAST).old_username := :OLD.username;
        v_audit_logs(v_audit_logs.LAST).new_username := :NEW.username;
    ELSIF DELETING THEN
        v_audit_logs(v_audit_logs.LAST).user_id := :OLD.user_id;
        v_audit_logs(v_audit_logs.LAST).action_type := 'DELETE';
        v_audit_logs(v_audit_logs.LAST).old_username := :OLD.username;
    END IF;
END AFTER EACH ROW;

AFTER STATEMENT IS
BEGIN
    IF v_audit_logs.COUNT > 0 THEN
        FORALL i IN 1 .. v_audit_logs.COUNT
            INSERT INTO user_audit_log (
                user_id,
                action_type,
                old_username,
                new_username,
                action_date
            ) VALUES (
                v_audit_logs(i).user_id,
                v_audit_logs(i).action_type,
                v_audit_logs(i).old_username,
                v_audit_logs(i).new_username,
                SYSDATE
            );
    END IF;
END AFTER STATEMENT;
END user_audit_trg;
/

CREATE OR REPLACE TRIGGER trg_prevent_negative_price
BEFORE INSERT OR UPDATE OF price ON games
FOR EACH ROW
BEGIN
    IF :NEW.price < 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Operation cancelled: Game price cannot be negative.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_update_wallet_time
BEFORE UPDATE OF balance ON wallets
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_add_to_library
AFTER INSERT OR UPDATE OF status ON purchases
FOR EACH ROW
BEGIN
    IF LOWER(:NEW.status) = 'completed' THEN
        IF INSERTING OR LOWER(NVL(:OLD.status, '~')) <> 'completed' THEN
            INSERT INTO library (game_id, user_id, purchase_id, added_date)
            SELECT pi.game_id,
                   :NEW.user_id,
                   :NEW.purchase_id,
                   CURRENT_TIMESTAMP
              FROM purchases_item pi
             WHERE pi.purchase_id = :NEW.purchase_id
               AND NOT EXISTS (
                   SELECT 1
                     FROM library l
                    WHERE l.user_id = :NEW.user_id
                      AND l.game_id = pi.game_id
               );
        END IF;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_friendship_cleanup
AFTER DELETE ON friends
FOR EACH ROW
BEGIN
    DELETE FROM messages
     WHERE (sender_id = :OLD.user_id AND receiver_id = :OLD.friend_id)
        OR (sender_id = :OLD.friend_id AND receiver_id = :OLD.user_id);
END;
/

CREATE OR REPLACE TRIGGER del_user_tr
BEFORE DELETE ON users
FOR EACH ROW
BEGIN
    DELETE FROM library WHERE user_id = :OLD.user_id;
    DELETE FROM wallets WHERE user_id = :OLD.user_id;

    DELETE FROM purchases_item
     WHERE purchase_id IN (
           SELECT purchase_id
             FROM purchases
            WHERE user_id = :OLD.user_id
     );

    DELETE FROM purchases WHERE user_id = :OLD.user_id;
    DELETE FROM user_achievements WHERE user_id = :OLD.user_id;
    DELETE FROM sessions WHERE user_id = :OLD.user_id;
    DELETE FROM friends WHERE user_id = :OLD.user_id OR friend_id = :OLD.user_id;
    DELETE FROM messages WHERE sender_id = :OLD.user_id OR receiver_id = :OLD.user_id;
    DELETE FROM reviews WHERE user_id = :OLD.user_id;
    DELETE FROM badges WHERE user_id = :OLD.user_id;
END;
/
