-- Raw index DDL copied from Oracle APEX Object Browser.

CREATE INDEX "IDX_ACHIEVEMENTS_GAME_ID" ON "ACHIEVEMENTS" ("GAME_ID");
CREATE INDEX "IDX_LIBRARY_USER_ID" ON "LIBRARY" ("USER_ID");
CREATE INDEX "IDX_MESSAGES_CONV" ON "MESSAGES" ("SENDER_ID", "RECEIVER_ID", SYS_EXTRACT_UTC("SENT_AT"));
CREATE INDEX "IDX_PURCHASES_USER_ID" ON "PURCHASES" ("USER_ID");
CREATE INDEX "IDX_SESSIONS_USER_END" ON "SESSIONS" ("USER_ID", SYS_EXTRACT_UTC("END_TIME"));
CREATE INDEX "IDX_SESSIONS_USER_GAME" ON "SESSIONS" ("USER_ID", "GAME_ID");
CREATE INDEX "IDX_UA_ACHIEVEMENT_ID" ON "USER_ACHIEVEMENTS" ("ACHIEVEMENT_ID");
CREATE INDEX "IDX_WALLETS_USER_UPDATED" ON "WALLETS" ("USER_ID", SYS_EXTRACT_UTC("UPDATED_AT"));

